# Artificial Neural Network

### Importing the libraries

In [23]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [24]:
tf.__version__ # Tensorflow version check

'2.15.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [25]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [26]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [27]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [28]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [29]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [31]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [32]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [33]:
# feature scaling is mandatory for deep learning
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [34]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [35]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu')) #number of neuron in 1st hidden layer we want have is 6 #activation='relu'rectifier activation function for fully connected neural network

### Adding the second hidden layer

In [36]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))# add method to add any number of layer

### Adding the output layer

In [37]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid')) # activation='sigmoid' we preditict output as 1 or 0 #sigmoid give the probability of result predicted so its better

## Part 3 - Training the ANN

### Compiling the ANN

In [38]:
# optimizer will update the weight for every iteration to reduce loss we use adam which is best
# loss we are working on binary outcome so we use loss = 'binary_crossentropy' and when we work on category we use cros entropy loss to find ,the loss function which is generated between actual and predicted difference
# metrics = ['accuracy'] to evaluvate we are using accuracy
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])


### Training the ANN on the Training set

In [39]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100) #batch_size = 32 we are compute and predicting the result in batches #epochs = 100 to make it learn better it should be high

Epoch 1/100
250/250 [==============================] - 1s 2ms/step - loss: 0.7481 - accuracy: 0.5725
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4988 - accuracy: 0.7941
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4589 - accuracy: 0.7968
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4385 - accuracy: 0.8096
Epoch 5/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4283 - accuracy: 0.8140
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4225 - accuracy: 0.8158
Epoch 7/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4182 - accuracy: 0.8174
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4145 - accuracy: 0.8200
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4107 - accuracy: 0.8226
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.4077 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation



Our ANN model to predict if the customer with the following informations will leave the bank:

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card ? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer ?

**Solution**

In [46]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]]))) #0.5 above means he will leave the bank or he won't

1/1 [==============================] - 0s 24ms/step
[[0.05124326]]


In [41]:
# france - 1, 0, 0
# Credit Score: 600
# Male - 1
# Age: 40 years old
# Tenure: 3 years
# Balance: $ 60000
# Number of Products: 2
# Does this customer have a credit card ? Yes -1
# Is this customer an Active Member: Yes -1
# Estimated Salary: $ 50000

print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5) #sc.transform we scale this single observation because we have applied scaling at the begining

1/1 [==============================] - 0s 34ms/step
[[False]]


Therefore, our ANN model predicts that this customer stays in the bank!

**Important note 1:** Notice that the values of the features were all input in a double pair of square brackets. That's because the "predict" method always expects a 2D array as the format of its inputs. And putting our values into a double pair of square brackets makes the input exactly a 2D array.

**Important note 2:** Notice also that the "France" country was not input as a string in the last column but as "1, 0, 0" in the first three columns. That's because of course the predict method expects the one-hot-encoded values of the state, and as we see in the first row of the matrix of features X, "France" was encoded as "1, 0, 0". And be careful to include these values in the first three columns, because the dummy variables are always created in the first columns.

### Predicting the Test set results

In [42]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5) #predicted probability is between 0 to 0.5 then it will store '0' and predicted probability is between 0.5 to 1 then it will store '1'
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 1s 8ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1514   81]
 [ 193  212]]


0.863